<?xml version="1.0"?>
<!DOCTYPE HPCToolkitExperiment [
<!-- ******************************************************************** -->
<!-- HPCToolkit Experiment DTD						  -->
<!-- Version 2.1							  -->
<!-- ******************************************************************** -->
<!ELEMENT HPCToolkitExperiment (Header, (SecCallPathProfile|SecFlatProfile)*)>
<!ATTLIST HPCToolkitExperiment
	  version CDATA #REQUIRED>

  <!-- ****************************************************************** -->

  <!-- Info/NV: flexible name-value pairs: (n)ame; (t)ype; (v)alue -->
  <!ELEMENT Info (NV*)>
  <!ATTLIST Info
	    n CDATA #IMPLIED>
  <!ELEMENT NV EMPTY>
  <!ATTLIST NV
	    n CDATA #REQUIRED
	    t CDATA #IMPLIED
	    v CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Header								  -->
  <!-- ****************************************************************** -->
  <!ELEMENT Header (Info*)>
  <!ATTLIST Header
	    n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section Header							  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecHeader (MetricTable?, MetricDBTable?, TraceDBTable?, LoadModuleTable?, FileTable?, ProcedureTable?, Info*)>

    <!-- MetricTable: -->
    <!ELEMENT MetricTable (Metric)*>

    <!-- Metric: (i)d; (n)ame -->
    <!--   (v)alue-type: transient type of values -->
    <!--   (t)ype: persistent type of metric -->
    <!--   fmt: format; show; -->
    <!ELEMENT Metric (MetricFormula*, Info?)>
    <!ATTLIST Metric
	      i            CDATA #REQUIRED
	      n            CDATA #REQUIRED
	      es	   CDATA #IMPLIED
	      em	   CDATA #IMPLIED
	      ep	   CDATA #IMPLIED
	      v            (raw|final|derived-incr|derived) "raw"
	      t            (inclusive|exclusive|nil) "nil"
	      partner      CDATA #IMPLIED
	      fmt          CDATA #IMPLIED
	      show         (1|0) "1"
	      show-percent (1|0) "1">

    <!-- MetricFormula represents derived metrics: (t)ype; (frm): formula -->
    <!ELEMENT MetricFormula (Info?)>
    <!ATTLIST MetricFormula
	      t   (combine|finalize) "finalize"
	      i   CDATA #IMPLIED
	      frm CDATA #REQUIRED>

    <!-- Metric data, used in sections: (n)ame [from Metric]; (v)alue -->
    <!ELEMENT M EMPTY>
    <!ATTLIST M
	      n CDATA #REQUIRED
	      v CDATA #REQUIRED>

    <!-- MetricDBTable: -->
    <!ELEMENT MetricDBTable (MetricDB)*>

    <!-- MetricDB: (i)d; (n)ame -->
    <!--   (t)ype: persistent type of metric -->
    <!--   db-glob:        file glob describing files in metric db -->
    <!--   db-id:          id within metric db -->
    <!--   db-num-metrics: number of metrics in db -->
    <!--   db-header-sz:   size (in bytes) of a db file header -->
    <!ELEMENT MetricDB EMPTY>
    <!ATTLIST MetricDB
	      i              CDATA #REQUIRED
	      n              CDATA #REQUIRED
	      t              (inclusive|exclusive|nil) "nil"
	      partner        CDATA #IMPLIED
	      db-glob        CDATA #IMPLIED
	      db-id          CDATA #IMPLIED
	      db-num-metrics CDATA #IMPLIED
	      db-header-sz   CDATA #IMPLIED>

    <!-- TraceDBTable: -->
    <!ELEMENT TraceDBTable (TraceDB)>

    <!-- TraceDB: (i)d -->
    <!--   db-min-time: min beginning time stamp (global) -->
    <!--   db-max-time: max ending time stamp (global) -->
    <!ELEMENT TraceDB EMPTY>
    <!ATTLIST TraceDB
	      i            CDATA #REQUIRED
	      db-glob      CDATA #IMPLIED
	      db-min-time  CDATA #IMPLIED
	      db-max-time  CDATA #IMPLIED
	      db-header-sz CDATA #IMPLIED>

    <!-- LoadModuleTable assigns a short name to a load module -->
    <!ELEMENT LoadModuleTable (LoadModule)*>

    <!ELEMENT LoadModule (Info?)>
    <!ATTLIST LoadModule
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- FileTable assigns a short name to a file -->
    <!ELEMENT FileTable (File)*>

    <!ELEMENT File (Info?)>
    <!ATTLIST File
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- ProcedureTable assigns a short name to a procedure -->
    <!ELEMENT ProcedureTable (Procedure)*>

    <!ELEMENT Procedure (Info?)>
    <!ATTLIST Procedure
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section: Call path profile					  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecCallPathProfile (SecHeader, SecCallPathProfileData)>
  <!ATTLIST SecCallPathProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecCallPathProfileData (PF|M)*>
      <!-- Procedure frame -->
      <!--   (i)d: unique identifier for cross referencing -->
      <!--   (s)tatic scope id -->
      <!--   (n)ame: a string or an id in ProcedureTable -->
      <!--   (lm) load module: a string or an id in LoadModuleTable -->
      <!--   (f)ile name: a string or an id in LoadModuleTable -->
      <!--   (l)ine range: "beg-end" (inclusive range) -->
      <!--   (a)lien: whether frame is alien to enclosing P -->
      <!--   (str)uct: hpcstruct node id -->
      <!--   (v)ma-range-set: "{[beg-end), [beg-end)...}" -->
      <!ELEMENT PF (PF|Pr|L|C|S|M)*>
      <!ATTLIST PF
		i  CDATA #IMPLIED
		s  CDATA #IMPLIED
		n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Procedure (static): GOAL: replace with 'P' -->
      <!ELEMENT Pr (Pr|L|C|S|M)*>
      <!ATTLIST Pr
                i  CDATA #IMPLIED
		s  CDATA #IMPLIED
                n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
                l  CDATA #IMPLIED
		a  (1|0) "0"
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Callsite (a special StatementRange) -->
      <!ELEMENT C (PF|M)*>
      <!ATTLIST C
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>

  <!-- ****************************************************************** -->
  <!-- Section: Flat profile						  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecFlatProfile (SecHeader, SecFlatProfileData)>
  <!ATTLIST SecFlatProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecFlatProfileData (LM|M)*>
      <!-- Load module: (i)d; (n)ame; (v)ma-range-set -->
      <!ELEMENT LM (F|P|M)*>
      <!ATTLIST LM
                i CDATA #IMPLIED
                n CDATA #REQUIRED
		v CDATA #IMPLIED>
      <!-- File -->
      <!ELEMENT F (P|L|S|M)*>
      <!ATTLIST F
                i CDATA #IMPLIED
                n CDATA #REQUIRED>
      <!-- Procedure (Note 1) -->
      <!ELEMENT P (P|A|L|S|C|M)*>
      <!ATTLIST P
                i CDATA #IMPLIED
                n CDATA #REQUIRED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Alien (Note 1) -->
      <!ELEMENT A (A|L|S|C|M)*>
      <!ATTLIST A
                i CDATA #IMPLIED
                f CDATA #IMPLIED
                n CDATA #IMPLIED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Loop (Note 1,2) -->
      <!ELEMENT L (A|Pr|L|S|C|M)*>
      <!ATTLIST L
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
	        f CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Statement (Note 2) -->
      <!--   (it): trace record identifier -->
      <!ELEMENT S (S|M)*>
      <!ATTLIST S
		i  CDATA #IMPLIED
		it CDATA #IMPLIED
		s  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Note 1: Contained Cs may not contain PFs -->
      <!-- Note 2: The 's' attribute is not used for flat profiles -->
]>
<HPCToolkitExperiment version="2.1">
<Header n="kripke">
  <Info/>
</Header>
<SecCallPathProfile i="0" n="kripke">
<SecHeader>
  <MetricTable>
    <Metric i="2" n="CPUTIME (usec):Sum (I)" v="derived-incr" em="0" es="0" ep="-9223372036854775808" t="inclusive" partner="3" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($2, $2)"/>
      <MetricFormula t="finalize" frm="$2"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="3" n="CPUTIME (usec):Sum (E)" v="derived-incr" em="0" es="0" ep="-9223372036854775808" t="exclusive" partner="2" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($3, $3)"/>
      <MetricFormula t="finalize" frm="$3"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
  </MetricTable>
  <MetricDBTable>
    <MetricDB i="0" n="CPUTIME (usec) (I)" t="inclusive" partner="1" db-glob="*.metric-db" db-id="0" db-num-metrics="2" db-header-sz="24"/>
    <MetricDB i="1" n="CPUTIME (usec) (E)" t="exclusive" partner="0" db-glob="*.metric-db" db-id="1" db-num-metrics="2" db-header-sz="24"/>
  </MetricDBTable>
  <LoadModuleTable>
    <LoadModule i="2" n="/g/g92/bhatele1/llnl/hpctoolkit/Kripke/build-mvapich2.3/kripke"/>
    <LoadModule i="1380" n="/collab/usr/global/tools/hpctoolkit/toss_3_x86_64_ib/2019-02-26/packages/linux-rhel7-x86_64/gcc-4.9.3/hpctoolkit-develop-szfcj5uplk66ruwembpihb7kexoonoti/lib/hpctoolkit/ext-libs/libmonitor.so.0.0.0"/>
    <LoadModule i="1392" n="/usr/tce/packages/mvapich2/mvapich2-2.3-intel-18.0.1/lib/libmpi.so.12.1.1"/>
    <LoadModule i="1676" n="/usr/tce/packages/gcc/gcc-4.9.3/lib64/libstdc++.so.6.0.20"/>
    <LoadModule i="1708" n="/usr/lib64/libc-2.17.so"/>
    <LoadModule i="1900" n="/usr/lib64/libdl-2.17.so"/>
    <LoadModule i="1909" n="/usr/lib64/libpthread-2.17.so"/>
    <LoadModule i="1913" n="/usr/lib64/ld-2.17.so"/>
    <LoadModule i="1930" n="/usr/lib64/libpsm2.so.2.1"/>
    <LoadModule i="2266" n="/usr/tce/packages/intel/intel-18.0.1/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64_lin/libintlc.so.5"/>
  </LoadModuleTable>
  <FileTable>
    <File i="3" n="&lt;unknown file&gt; [kripke]"/>
    <File i="1381" n="&lt;unknown file&gt; [libmonitor.so.0.0.0]"/>
    <File i="1393" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/init/init.c"/>
    <File i="1396" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/init/initthread.c"/>
    <File i="1399" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/src/mpid_init.c"/>
    <File i="1402" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/channels/psm/src/psm_entry.c"/>
    <File i="1405" n="/builddir/build/BUILD/mvapich2-2.3/src/openpa/src/primitives/opa_gcc_intel_32_64_ops.h"/>
    <File i="1408" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/timer/wtime.c"/>
    <File i="1411" n="&lt;unknown file&gt; [libmpi.so.12.1.1]"/>
    <File i="1414" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/pt2pt/irecv.c"/>
    <File i="1417" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/src/mpid_irecv.c"/>
    <File i="1420" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/src/ch3u_request.c"/>
    <File i="1423" n="/builddir/build/BUILD/mvapich2-2.3/src/util/mem/handlemem.c"/>
    <File i="1428" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/channels/psm/src/psm_recv.c"/>
    <File i="1433" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/pt2pt/waitall.c"/>
    <File i="1439" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/channels/psm/src/psm_queue.c"/>
    <File i="1447" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/pt2pt/mpir_request.c"/>
    <File i="1452" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/pt2pt/testany.c"/>
    <File i="1495" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/channels/psm/src/mpidi_calls.c"/>
    <File i="1539" n="/builddir/build/BUILD/mvapich2-2.3/src/util/timers/mpiu_timer.c"/>
    <File i="1543" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/pt2pt/isend.c"/>
    <File i="1546" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/src/mpid_isend.c"/>
    <File i="1554" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/src/ch3u_eager.c"/>
    <File i="1558" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/channels/psm/src/psm_istart.c"/>
    <File i="1564" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/channels/psm/src/psm_send.c"/>
    <File i="1568" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/debugger/dbginit.c"/>
    <File i="1571" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/reduce.c"/>
    <File i="1576" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/reduce_osu.c"/>
    <File i="1583" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/helper_fns.c"/>
    <File i="1589" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/src/mpid_recv.c"/>
    <File i="1600" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/src/mpid_send.c"/>
    <File i="1614" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/ch3_shmem_coll.c"/>
    <File i="1623" n="./src/usr/include/pthread.h"/>
    <File i="1626" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/comm/create_2level_comm.c"/>
    <File i="1632" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/allreduce.c"/>
    <File i="1635" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/allreduce_osu.c"/>
    <File i="1657" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/barrier.c"/>
    <File i="1662" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/barrier_osu.c"/>
    <File i="1677" n="/tmp/mockbuild/spack-stage/spack-stage-P3jF0z/spack-build/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_string.h"/>
    <File i="1680" n="/tmp/mockbuild/spack-stage/spack-stage-P3jF0z/spack-build/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc"/>
    <File i="1683" n="/tmp/mockbuild/spack-stage/spack-stage-P3jF0z/spack-build/x86_64-unknown-linux-gnu/libstdc++-v3/include/ext/new_allocator.h"/>
    <File i="1686" n="&lt;unknown file&gt; [libstdc++.so.6.0.20]"/>
    <File i="1689" n="/builddir/build/BUILD/gccspack/spack/var/spack/stage/gcc-4.9.3-34vmmvov5ct2riknhkfcmxieffb5pyex/gcc-4.9.3/libstdc++-v3/libsupc++/new_op.cc"/>
    <File i="1694" n="/builddir/build/BUILD/gccspack/spack/var/spack/stage/gcc-4.9.3-34vmmvov5ct2riknhkfcmxieffb5pyex/gcc-4.9.3/libstdc++-v3/libsupc++/del_op.cc"/>
    <File i="1701" n="/tmp/mockbuild/spack-stage/spack-stage-P3jF0z/spack-build/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/char_traits.h"/>
    <File i="1705" n="/tmp/mockbuild/spack-stage/spack-stage-P3jF0z/spack-build/x86_64-unknown-linux-gnu/libstdc++-v3/include/ext/atomicity.h"/>
    <File i="1709" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/x86_64/memset.S"/>
    <File i="1718" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/unix/clock_gettime.c"/>
    <File i="1726" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/x86_64/multiarch/memcpy-ssse3-back.S"/>
    <File i="1729" n="./src/usr/src/debug/glibc-2.17-c758a686/malloc/malloc.c"/>
    <File i="1738" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/unix/syscall-template.S"/>
    <File i="1787" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/unix/sysv/linux/writev.c"/>
    <File i="1881" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/x86_64/multiarch/strlen-sse2-pminub.S"/>
    <File i="1884" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/x86_64/multiarch/memcmp-sse4.S"/>
    <File i="1887" n="./src/usr/src/debug/glibc-2.17-c758a686/nptl/forward.c"/>
    <File i="1890" n="./src/usr/src/debug/glibc-2.17-c758a686/elf/dl-sym.c"/>
    <File i="1893" n="./src/usr/src/debug/glibc-2.17-c758a686/stdlib/getenv.c"/>
    <File i="1901" n="./src/usr/src/debug/glibc-2.17-c758a686/dlfcn/dlsym.c"/>
    <File i="1904" n="./src/usr/src/debug/glibc-2.17-c758a686/dlfcn/dlerror.c"/>
    <File i="1910" n="./src/usr/src/debug/glibc-2.17-c758a686/nptl/sysdeps/x86_64/pthread_spin_lock.S"/>
    <File i="1914" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/x86_64/dl-trampoline.h"/>
    <File i="1917" n="./src/usr/src/debug/glibc-2.17-c758a686/elf/dl-runtime.c"/>
    <File i="1920" n="./src/usr/src/debug/glibc-2.17-c758a686/elf/dl-lookup.c"/>
    <File i="1926" n="./src/usr/src/debug/glibc-2.17-c758a686/elf/dl-error.c"/>
    <File i="1931" n="&lt;unknown file&gt; [libpsm2.so.2.1]"/>
    <File i="2267" n="&lt;unknown file&gt; [libintlc.so.5]"/>
  </FileTable>
  <ProcedureTable>
    <Procedure i="38" n="memset@plt"/>
    <Procedure i="66" n="operator delete(void*)@plt"/>
    <Procedure i="70" n="operator new(unsigned long)@plt"/>
    <Procedure i="104" n="MPI_Testany@plt"/>
    <Procedure i="158" n="main"/>
    <Procedure i="260" n="Grid_Data::particleEdit"/>
    <Procedure i="590" n="std::vector&lt;int, std::allocator&lt;int&gt; &gt;::_M_insert_aux"/>
    <Procedure i="592" n="SweepSubdomains"/>
    <Procedure i="598" n="SweepSolver"/>
    <Procedure i="632" n="Timing::start"/>
    <Procedure i="636" n="Timing::stop"/>
    <Procedure i="814" n="Kernel_3d_DGZ::LTimes"/>
    <Procedure i="828" n="Kernel_3d_DGZ::LPlusTimes"/>
    <Procedure i="840" n="Kernel_3d_DGZ::scattering"/>
    <Procedure i="854" n="Kernel_3d_DGZ::source"/>
    <Procedure i="862" n="Kernel_3d_DGZ::sweep"/>
    <Procedure i="1208" n="SweepComm::readySubdomains"/>
    <Procedure i="1210" n="SweepComm::markComplete"/>
    <Procedure i="1214" n="SweepComm::workRemaining"/>
    <Procedure i="1310" n="ParallelComm::workRemaining"/>
    <Procedure i="1330" n="ParallelComm::waitAllSends"/>
    <Procedure i="1334" n="ParallelComm::testRecieves"/>
    <Procedure i="1342" n="ParallelComm::postSends"/>
    <Procedure i="1358" n="ParallelComm::getReadyList"/>
    <Procedure i="1362" n="ParallelComm::postRecvs"/>
    <Procedure i="1366" n="std::vector&lt;Subdomain*, std::allocator&lt;Subdomain*&gt; &gt;::_M_insert_aux"/>
    <Procedure i="1382" n="&lt;program root&gt;" f="1"/>
    <Procedure i="1384" n="MPI_Init"/>
    <Procedure i="1386" n="pthread_create"/>
    <Procedure i="1388" n="MPI_Comm_rank"/>
    <Procedure i="1390" n="PMPI_Comm_rank"/>
    <Procedure i="1394" n="PMPI_Init"/>
    <Procedure i="1397" n="MPIR_Init_thread"/>
    <Procedure i="1400" n="MPID_Init"/>
    <Procedure i="1403" n="psm_doinit"/>
    <Procedure i="1406" n="OPA_load_int"/>
    <Procedure i="1409" n="PMPI_Wtime"/>
    <Procedure i="1412" n="&lt;unknown procedure&gt; 0x142440 [libmpi.so.12.1.1]"/>
    <Procedure i="1470" n="&lt;unknown procedure&gt; 0x143100 [libmpi.so.12.1.1]"/>
    <Procedure i="1474" n="&lt;unknown procedure&gt; 0x140b40 [libmpi.so.12.1.1]"/>
    <Procedure i="1491" n="&lt;unknown procedure&gt; 0x142f30 [libmpi.so.12.1.1]"/>
    <Procedure i="1493" n="&lt;unknown procedure&gt; 0x144b30 [libmpi.so.12.1.1]"/>
    <Procedure i="1504" n="&lt;unknown procedure&gt; 0x13f5a0 [libmpi.so.12.1.1]"/>
    <Procedure i="1533" n="&lt;unknown procedure&gt; 0x142a90 [libmpi.so.12.1.1]"/>
    <Procedure i="1415" n="PMPI_Irecv"/>
    <Procedure i="1418" n="MPID_Irecv"/>
    <Procedure i="1421" n="MPID_Request_create"/>
    <Procedure i="1450" n="MPIDI_CH3_Request_destroy"/>
    <Procedure i="1424" n="MPIU_Handle_indirect_init"/>
    <Procedure i="1550" n="MPIU_Handle_obj_alloc_unsafe"/>
    <Procedure i="1476" n="MPIU_Handle_get_ptr_indirect"/>
    <Procedure i="1592" n="psm_recv"/>
    <Procedure i="1429" n="psm_irecv"/>
    <Procedure i="1436" n="MPIR_Waitall_impl"/>
    <Procedure i="1434" n="PMPI_Waitall"/>
    <Procedure i="1513" n="psm_complete_req"/>
    <Procedure i="1511" n="psm_process_completion"/>
    <Procedure i="1594" n="psm_try_complete"/>
    <Procedure i="1440" n="psm_progress_wait"/>
    <Procedure i="1502" n="psm_no_lock"/>
    <Procedure i="1516" n="psm_update_mpistatus"/>
    <Procedure i="1448" n="MPIR_Request_complete"/>
    <Procedure i="1453" n="PMPI_Testany"/>
    <Procedure i="1646" n="MPIDI_CH3_Progress_start"/>
    <Procedure i="1496" n="MPIDI_CH3_Progress_test"/>
    <Procedure i="1540" n="MPIU_Wtime_todouble"/>
    <Procedure i="1544" n="PMPI_Isend"/>
    <Procedure i="1547" n="MPID_Isend"/>
    <Procedure i="1603" n="MPIDI_CH3_EagerContigSend"/>
    <Procedure i="1555" n="MPIDI_CH3_EagerContigIsend"/>
    <Procedure i="1605" n="psm_istartmsgv"/>
    <Procedure i="1559" n="psm_isendv"/>
    <Procedure i="1607" n="psm_send_pkt"/>
    <Procedure i="1565" n="psm_isend_pkt"/>
    <Procedure i="1569" n="MPIR_Sendq_remember"/>
    <Procedure i="1574" n="MPIR_Reduce_impl"/>
    <Procedure i="1572" n="PMPI_Reduce"/>
    <Procedure i="1581" n="MPIR_Reduce_binomial_MV2"/>
    <Procedure i="1612" n="MPIR_Reduce_shmem_MV2"/>
    <Procedure i="1610" n="MPIR_Reduce_two_level_helper_MV2"/>
    <Procedure i="1579" n="MPIR_Reduce_index_tuned_intra_MV2"/>
    <Procedure i="1577" n="MPIR_Reduce_MV2"/>
    <Procedure i="1584" n="MPIR_Localcopy"/>
    <Procedure i="1644" n="MPIC_Wait"/>
    <Procedure i="1598" n="MPIC_Send"/>
    <Procedure i="1587" n="MPIC_Recv"/>
    <Procedure i="1642" n="MPIC_Sendrecv"/>
    <Procedure i="1590" n="MPID_Recv"/>
    <Procedure i="1601" n="MPID_Send"/>
    <Procedure i="1615" n="MPIDI_CH3I_SHMEM_COLL_GetShmemBuf"/>
    <Procedure i="1672" n="MPIDI_CH3I_SHMEM_COLL_Barrier_bcast"/>
    <Procedure i="1621" n="mv2_increment_shmem_coll_counter"/>
    <Procedure i="1651" n="mv2_shm_coll_init"/>
    <Procedure i="1624" n="pthread_equal"/>
    <Procedure i="1630" n="create_2level_comm"/>
    <Procedure i="1627" n="check_split_comm"/>
    <Procedure i="1633" n="MPIR_Allreduce_impl"/>
    <Procedure i="1640" n="MPIR_Allreduce_pt2pt_rd_MV2"/>
    <Procedure i="1636" n="MPIR_Allreduce_index_tuned_intra_MV2"/>
    <Procedure i="1660" n="MPIR_Barrier_impl"/>
    <Procedure i="1658" n="PMPI_Barrier"/>
    <Procedure i="1667" n="MPIR_Pairwise_Barrier_MV2"/>
    <Procedure i="1670" n="MPIR_shmem_barrier_MV2"/>
    <Procedure i="1665" n="MPIR_Barrier_intra_MV2"/>
    <Procedure i="1663" n="MPIR_Barrier_MV2"/>
    <Procedure i="1678" n="std::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;::basic_string(char const*, std::allocator&lt;char&gt; const&amp;)"/>
    <Procedure i="1681" n="char* std::string::_S_construct&lt;char const*&gt;(char const*, char const*, std::allocator&lt;char&gt; const&amp;, std::forward_iterator_tag)"/>
    <Procedure i="1684" n="std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator&lt;char&gt; const&amp;)"/>
    <Procedure i="1687" n="&lt;unknown procedure&gt; 0x58860 [libstdc++.so.6.0.20]"/>
    <Procedure i="1692" n="&lt;unknown procedure&gt; 0x59340 [libstdc++.so.6.0.20]"/>
    <Procedure i="1698" n="&lt;unknown procedure&gt; 0x58c10 [libstdc++.so.6.0.20]"/>
    <Procedure i="1690" n="operator new(unsigned long)"/>
    <Procedure i="1695" n="operator delete(void*)"/>
    <Procedure i="1702" n="std::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;::basic_string(char const*, std::allocator&lt;char&gt; const&amp;)"/>
    <Procedure i="1706" n="std::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;::basic_string(std::string const&amp;)"/>
    <Procedure i="1710" n="__memset_sse2"/>
    <Procedure i="1719" n="__GI___clock_gettime"/>
    <Procedure i="1727" n="__memmove_ssse3_back"/>
    <Procedure i="1755" n="alloc_perturb"/>
    <Procedure i="1807" n="free_perturb"/>
    <Procedure i="1730" n="__GI___libc_malloc"/>
    <Procedure i="1824" n="__GI___libc_free"/>
    <Procedure i="1733" n="__libc_calloc"/>
    <Procedure i="1735" n="_int_malloc"/>
    <Procedure i="1792" n="_int_free"/>
    <Procedure i="1760" n="malloc_printerr"/>
    <Procedure i="1739" n="__GI_process_vm_readv"/>
    <Procedure i="1790" n="__ioctl"/>
    <Procedure i="1896" n="__open_nocancel"/>
    <Procedure i="1898" n="__unlink"/>
    <Procedure i="1788" n="__libc_writev"/>
    <Procedure i="1882" n="__strlen_sse2_pminub"/>
    <Procedure i="1885" n="__memcmp_sse4_1"/>
    <Procedure i="1888" n="pthread_mutex_unlock"/>
    <Procedure i="1891" n="do_sym"/>
    <Procedure i="1894" n="__GI_getenv"/>
    <Procedure i="1907" n="dlsym_doit"/>
    <Procedure i="1902" n="__dlsym"/>
    <Procedure i="1905" n="_dlerror_run"/>
    <Procedure i="1911" n="pthread_spin_lock"/>
    <Procedure i="1915" n="_dl_runtime_resolve_xsave"/>
    <Procedure i="1918" n="_dl_fixup"/>
    <Procedure i="1923" n="do_lookup_x"/>
    <Procedure i="1921" n="_dl_lookup_symbol_x"/>
    <Procedure i="1927" n="_dl_catch_error"/>
    <Procedure i="1932" n="&lt;unknown procedure&gt; 0x11464 [libpsm2.so.2.1]"/>
    <Procedure i="1934" n="&lt;unknown procedure&gt; 0x10d0c [libpsm2.so.2.1]"/>
    <Procedure i="1936" n="&lt;unknown procedure&gt; 0x22c49 [libpsm2.so.2.1]"/>
    <Procedure i="1938" n="&lt;unknown procedure&gt; 0x23ea2 [libpsm2.so.2.1]"/>
    <Procedure i="1940" n="&lt;unknown procedure&gt; 0x1ad28 [libpsm2.so.2.1]"/>
    <Procedure i="1942" n="&lt;unknown procedure&gt; 0x1ae6b [libpsm2.so.2.1]"/>
    <Procedure i="1944" n="&lt;unknown procedure&gt; 0xcfda [libpsm2.so.2.1]"/>
    <Procedure i="1946" n="&lt;unknown procedure&gt; 0xd986 [libpsm2.so.2.1]"/>
    <Procedure i="1948" n="&lt;unknown procedure&gt; 0x1b034 [libpsm2.so.2.1]"/>
    <Procedure i="1950" n="&lt;unknown procedure&gt; 0x1d47f [libpsm2.so.2.1]"/>
    <Procedure i="1952" n="&lt;unknown procedure&gt; 0x1f032 [libpsm2.so.2.1]"/>
    <Procedure i="1954" n="&lt;unknown procedure&gt; 0x1f035 [libpsm2.so.2.1]"/>
    <Procedure i="1956" n="&lt;unknown procedure&gt; 0x1b740 [libpsm2.so.2.1]"/>
    <Procedure i="1958" n="&lt;unknown procedure&gt; 0x1b746 [libpsm2.so.2.1]"/>
    <Procedure i="1960" n="&lt;unknown procedure&gt; 0x1b754 [libpsm2.so.2.1]"/>
    <Procedure i="1962" n="&lt;unknown procedure&gt; 0x1b75b [libpsm2.so.2.1]"/>
    <Procedure i="1964" n="&lt;unknown procedure&gt; 0x1b7b1 [libpsm2.so.2.1]"/>
    <Procedure i="1966" n="&lt;unknown procedure&gt; 0x1b7b2 [libpsm2.so.2.1]"/>
    <Procedure i="1968" n="&lt;unknown procedure&gt; 0x1b7c9 [libpsm2.so.2.1]"/>
    <Procedure i="1970" n="&lt;unknown procedure&gt; 0x1b7d6 [libpsm2.so.2.1]"/>
    <Procedure i="1972" n="&lt;unknown procedure&gt; 0x1b7de [libpsm2.so.2.1]"/>
    <Procedure i="1974" n="&lt;unknown procedure&gt; 0x1b7e7 [libpsm2.so.2.1]"/>
    <Procedure i="1976" n="&lt;unknown procedure&gt; 0x21372 [libpsm2.so.2.1]"/>
    <Procedure i="1978" n="&lt;unknown procedure&gt; 0x21379 [libpsm2.so.2.1]"/>
    <Procedure i="1980" n="&lt;unknown procedure&gt; 0x213a8 [libpsm2.so.2.1]"/>
    <Procedure i="1982" n="&lt;unknown procedure&gt; 0x213b6 [libpsm2.so.2.1]"/>
    <Procedure i="1984" n="&lt;unknown procedure&gt; 0x22590 [libpsm2.so.2.1]"/>
    <Procedure i="1986" n="&lt;unknown procedure&gt; 0x22594 [libpsm2.so.2.1]"/>
    <Procedure i="1988" n="&lt;unknown procedure&gt; 0x22599 [libpsm2.so.2.1]"/>
    <Procedure i="1990" n="&lt;unknown procedure&gt; 0x2259e [libpsm2.so.2.1]"/>
    <Procedure i="1992" n="&lt;unknown procedure&gt; 0x225ab [libpsm2.so.2.1]"/>
    <Procedure i="1994" n="&lt;unknown procedure&gt; 0x22607 [libpsm2.so.2.1]"/>
    <Procedure i="1996" n="&lt;unknown procedure&gt; 0x2260e [libpsm2.so.2.1]"/>
    <Procedure i="1998" n="&lt;unknown procedure&gt; 0x22610 [libpsm2.so.2.1]"/>
    <Procedure i="2000" n="&lt;unknown procedure&gt; 0x22638 [libpsm2.so.2.1]"/>
    <Procedure i="2002" n="&lt;unknown procedure&gt; 0x2264a [libpsm2.so.2.1]"/>
    <Procedure i="2004" n="&lt;unknown procedure&gt; 0x22654 [libpsm2.so.2.1]"/>
    <Procedure i="2006" n="&lt;unknown procedure&gt; 0x2265a [libpsm2.so.2.1]"/>
    <Procedure i="2008" n="&lt;unknown procedure&gt; 0x213c8 [libpsm2.so.2.1]"/>
    <Procedure i="2010" n="&lt;unknown procedure&gt; 0x213d1 [libpsm2.so.2.1]"/>
    <Procedure i="2012" n="&lt;unknown procedure&gt; 0x213d6 [libpsm2.so.2.1]"/>
    <Procedure i="2014" n="&lt;unknown procedure&gt; 0xc9e1 [libpsm2.so.2.1]"/>
    <Procedure i="2016" n="&lt;unknown procedure&gt; 0xc9eb [libpsm2.so.2.1]"/>
    <Procedure i="2018" n="&lt;unknown procedure&gt; 0xc9f6 [libpsm2.so.2.1]"/>
    <Procedure i="2020" n="&lt;unknown procedure&gt; 0xc9fb [libpsm2.so.2.1]"/>
    <Procedure i="2022" n="&lt;unknown procedure&gt; 0xca5b [libpsm2.so.2.1]"/>
    <Procedure i="2024" n="&lt;unknown procedure&gt; 0xca72 [libpsm2.so.2.1]"/>
    <Procedure i="2026" n="&lt;unknown procedure&gt; 0x213d7 [libpsm2.so.2.1]"/>
    <Procedure i="2028" n="&lt;unknown procedure&gt; 0x213ee [libpsm2.so.2.1]"/>
    <Procedure i="2030" n="&lt;unknown procedure&gt; 0x213f5 [libpsm2.so.2.1]"/>
    <Procedure i="2032" n="&lt;unknown procedure&gt; 0x1b808 [libpsm2.so.2.1]"/>
    <Procedure i="2034" n="&lt;unknown procedure&gt; 0x1b742 [libpsm2.so.2.1]"/>
    <Procedure i="2036" n="&lt;unknown procedure&gt; 0x1b749 [libpsm2.so.2.1]"/>
    <Procedure i="2038" n="&lt;unknown procedure&gt; 0x1b74a [libpsm2.so.2.1]"/>
    <Procedure i="2040" n="&lt;unknown procedure&gt; 0x1b751 [libpsm2.so.2.1]"/>
    <Procedure i="2042" n="&lt;unknown procedure&gt; 0x1b7c0 [libpsm2.so.2.1]"/>
    <Procedure i="2044" n="&lt;unknown procedure&gt; 0x1b7cb [libpsm2.so.2.1]"/>
    <Procedure i="2046" n="&lt;unknown procedure&gt; 0x1b7d0 [libpsm2.so.2.1]"/>
    <Procedure i="2048" n="&lt;unknown procedure&gt; 0x1b7d2 [libpsm2.so.2.1]"/>
    <Procedure i="2050" n="&lt;unknown procedure&gt; 0x213b1 [libpsm2.so.2.1]"/>
    <Procedure i="2052" n="&lt;unknown procedure&gt; 0x2259c [libpsm2.so.2.1]"/>
    <Procedure i="2054" n="&lt;unknown procedure&gt; 0x225cf [libpsm2.so.2.1]"/>
    <Procedure i="2056" n="&lt;unknown procedure&gt; 0x225f1 [libpsm2.so.2.1]"/>
    <Procedure i="2058" n="&lt;unknown procedure&gt; 0x259d0 [libpsm2.so.2.1]"/>
    <Procedure i="2060" n="&lt;unknown procedure&gt; 0x32429 [libpsm2.so.2.1]"/>
    <Procedure i="2062" n="&lt;unknown procedure&gt; 0x2c127 [libpsm2.so.2.1]"/>
    <Procedure i="2064" n="&lt;unknown procedure&gt; 0x2a567 [libpsm2.so.2.1]"/>
    <Procedure i="2066" n="&lt;unknown procedure&gt; 0x29a27 [libpsm2.so.2.1]"/>
    <Procedure i="2068" n="&lt;unknown procedure&gt; 0x3321d [libpsm2.so.2.1]"/>
    <Procedure i="2070" n="&lt;unknown procedure&gt; 0x32164 [libpsm2.so.2.1]"/>
    <Procedure i="2072" n="&lt;unknown procedure&gt; 0x29917 [libpsm2.so.2.1]"/>
    <Procedure i="2074" n="&lt;unknown procedure&gt; 0x276b7 [libpsm2.so.2.1]"/>